name: Lint check external resources

on:
    push:
        paths:
            - 'external/**'

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./external
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 8.6.1

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'pnpm'
                  cache-dependency-path: 'external/pnpm-lock.yaml'

            - name: Install dependencies
              run: pnpm install

            - name: Run pnpm lint
              run: pnpm lint
