name: Deploy GitHub pages

on:
    push:
        paths:
            - 'external/**'

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./external
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 8.6.1

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'pnpm'
                  cache-dependency-path: './external/pnpm-lock.yaml'

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: './external/dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
